#!/bin/bash -ex
JENKINS_HOME=$1
sudo -u jenkins sed -i -e 's|<disabled>true|<disabled>false|' ${JENKINS_HOME}/jobs/jenkins-disable-nodes/config.xml
JENKINS_CLI="sudo -u jenkins java -jar ${JENKINS_HOME}/jenkins-cli.jar -i ${JENKINS_HOME}/.ssh/id_dsa -s http://localhost:8080/jenkins -remoting"
$JENKINS_CLI reload-job jenkins-disable-nodes
$JENKINS_CLI build jenkins-disable-nodes -p NODES_FILTER='.*'
$JENKINS_CLI enable-job jenkins-initialize
$JENKINS_CLI build 'jenkins-initialize'
