#!/bin/bash -ex
JENKINS_HOME=$1
SSHD_PORT=$(grep '<port>' $JENKINS_HOME/org.jenkinsci.main.modules.sshd.SSHD.xml | sed 's|</.*||;s|.*>||')
sed -i -e 's|<disabled>true|<disabled>false|' ${JENKINS_HOME}/jobs/jenkins-disable-nodes/config.xml
JENKINS_CLI="ssh -o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $LOCALCLI_KEY -l localcli -p ${SSHD_PORT} localhost"
$JENKINS_CLI reload-job jenkins-disable-nodes
$JENKINS_CLI build jenkins-disable-nodes -p NODES_FILTER='.*'
$JENKINS_CLI enable-job jenkins-initialize
$JENKINS_CLI build 'jenkins-initialize'
