#!/bin/bash -ex
JENKINS_HOME=$1
REPO=$2
script_dir=$(dirname $0)
branch=$(java -jar ${JENKINS_HOME}/jenkins-cli.jar -s http://localhost:8080/jenkins version | cut -d. -f1,2 | sed 's|.$||;s|\.$|\.0|')
if [ "X$branch" = "X" ] ; then 
  echo "Error: Unable to find jenkins version"
  exit 1
fi
GIT_BRANCH=jenkins${branch}
GIT_DIR=${JENKINS_HOME}/plugin-ref/cmsjenkins-${branch}
if [ ! -d $GIT_DIR ] ; then
  git clone --depth 1 -b $GIT_BRANCH $REPO $GIT_DIR
fi

find $GIT_DIR -name '*.xml' -type f | xargs grep ' plugin=' | sed 's|.* plugin="||;s|@.*||' | grep -v '^pipeline-' > $GIT_DIR/plugin.used
echo 'matrix-auth' >> $GIT_DIR/plugin.used
rm -rf $GIT_DIR/plugins.filter
touch $GIT_DIR/plugins.filter
for p in $(cat $GIT_DIR/plugin.used | sort -u) ; do
  grep "^$p:" $GIT_DIR/pluginslist >> $GIT_DIR/plugins.filter || true
done
rm -rf ${JENKINS_HOME}/plugin-ref/plugins/*.lock
${script_dir}/install-plugins.sh $GIT_DIR/pluginslist $GIT_DIR/plugins.filter

rsync -av --delete ${JENKINS_HOME}/plugin-ref/plugins/ ${JENKINS_HOME}/plugins/
for xml in $(ls $GIT_DIR/*.xml) ; do cp -f $xml $JENKINS_HOME/ ; done
for dir in labels users nodes log scriptler jobs ; do
  mkdir -p ${JENKINS_HOME}/${dir}
  rsync -av $GIT_DIR/${dir}/ ${JENKINS_HOME}/${dir}/
done

find ${JENKINS_HOME}/jobs -folow -mindepth 2 -maxdepth 2 -name 'config.xml' -type f |  xargs -i sed -i -e 's|<disabled>false|<disabled>true|' '{}'

mkdir -p  ${JENKINS_HOME}/secrets
. ${script_dir}/jenkins-secrets
for s in ${JENKINS_SECRETS_FILES}  ; do
  if [ ! -f $GIT_DIR/${s}.enc ] ; then continue ; fi
  openssl enc -d -a -base64 -aes-256-cbc -in $GIT_DIR/${s}.enc -out $JENKINS_HOME/$s -pass file:${JENKINS_HOME}/.ssh/id_dsa
done
